### PR TITLE
sample inbox implementation

### PR DESCRIPTION
**Pull request by bill-torpey**
I've come up with an implementation of inboxes that I think addresses the points raised in https://github.com/fquinner/OpenMAMA-zmq/issues/16 -- and I'm very interested in your thoughts on the overall approach, as well as the details of this particular implementation.  

I hope you'll have time to at least give things a look and provide some feedback -- while I'm certainly familiar with Mama (and a little with OpenMAMA), I'm a total noob when it comes to zmq. Also, it occurs to me that you likely had some ideas when you put this together that I'm not picking up on, so any pointers there would be much appreciated.

(Note that there are a couple of minor fixes mingled in with the pull request -- I wasn't sure if it was worth the trouble to create separate pull requests for these, and decided against it for now.  You'll know them when you see them).

Thanks!

### CODE REVIEW

**Comment by bill-torpey** [comment]
### Inbox topic
The zmq code generates a unique topic for each inbox, which causes problems since zmq filters subscriptions at the publisher (see https://github.com/fquinner/OpenMAMA-zmq/issues/16).

I modified the code to use "reply handles", which encode both a non-unique topic ("_INBOX.{hostname}.{pid}") and a unique subscriber ID.  This eliminates the race condition for the topic, but still provides for unique inboxes for request/reply messaging.

This approach is reasonable, given that even if we could use a unique topic for each inbox, the subscriber code would still have to filter and forward messages coming off the wire, although that would be done in the zmq library rather than in the zmq transport.  With the current approach messages are filtered somewhat lower down in the call stack, and it may be possible to improve performance somewhat by pushing that filtering higher up in the call stack.

Another approach which would likely perform better would be to have a direct socket connection for replies, bypassing the pub/sub channel.  This is the approach used by Wombat, and also by TibRV when direct communication is used. That approach would, however, involve a lot more time and effort

**Comment by bill-torpey** [comment]
#### Subscriptions
A race condition exists with respect to the subscription object that was being passed from `zmqBridgeMamaTransportImpl_dispatchThread` to `zmqBridgeMamaTransportImpl_queueCallback`.  Since these functions run on separate threads, the subscription object could be (and often was) deleted by the time it was dequeued on the second thread.  

The solution I chose was to pass (a copy of) the endpoint identifier instead of the subscription object itself.  Since `zmqBridgeMamaTransportImpl_queueCallback` was already looking up the subscription in the endpoint pool (by content rather than by identifier), the lookup doesn't cost anything and is probably faster (since `endpointPool_isRegistedByContent` iterates over the table, as opposed to `endpointPool_getEndpointByIdentifiers`, which does a direct lookup).

There is no other synchronization for subscription object, and that should be fine -- they are only deleted on the callback thread (via _destroyEx).  (They can of course be created on any thread, which is one of the reasons the synchronization of the endpoint pool discussed in #19 is necessary).

There is a small "window" here where a subscription can exist at the time the zmq message is taken off the wire (`zmq_recv` in `zmqBridgeMamaTransportImpl_dispatchThread`), but have been deleted by the time it is queried (in `zmqBridgeMamaTransportImpl_queueCallback`).      Since the endpoint pool is queried (again) on the callback thread, and since subscriptions can only be destroyed on the callback thread, this *should* work.

#### Caveats
- Given the above, it follows that in a simple single-threaded application , the above should never happen.  But it does, something like .0025% of the time  (5 out of 200,000) -- although in some runs not at all.  I don't (yet) have an answer for this.
- The endpoint identifier is strdup'd, which obviously imposes an additional malloc/free on every message. It would be nice to get rid of that overhead somehow.

**Comment by bill-torpey** [comment]
### Leaks in callback thread
The IO thread allocates memory that is enqueued to the callback thread, and which should be dellocated by it.  In some cases the callback thread returned without freeing the memory, which caused it to leak.  I modified the early return code in the callback thread (using `goto`;-) to make sure that all returns from the callback function free memory properly.

**Comment by fquinner** [comment]
Hi Bill - sorry it has taken over a year to finally dig through this! I did have a quick look at the time but I couldn't see how the changes fixed the problem and I never had the time to give it the attention I wanted to.

Don't know if you're still looking in this area but I just fired it up though and it doesn't look to be behaving as I expected it to. The reply is being sent out on the publisher's topic, which means the subscriber must be subscribed to the publisher's topic in order to receive the reply. The main test for request / response in pure MAMA is:

    mamapublisherc -m zmq -tport pub
    mamainboxc -m zmq -tport sub

This doesn't work with this code because the reply is sent over the publisher's topic which is `MAMA_TOPIC` which `mamainboxc` isn't subscribed to. Using this approach where the effective topic is the publisher's topic means that responses are broadcast to all consumers (which in itself isn't necessarily a problem - traditional Wombat feed handlers actually have a parameter to make them behave like this, but it does break an established OpenMAMA convention to assume this behaviour).

Honestly I never really liked the request reply implementation for the zmq bridge. It was lifted from qpid and is a little noisy for my taste. ZMQ does have a native request / reply pattern but it will definitely take a little work to get right, but I think that is ultimately the right choice longer term. Thread-local sockets are always the challenge in getting the zmq bridge right.

In the meantime it might work better if we simply publish replies over the deterministic `_INBOX.{hostname}.{pid}` topic and subscribe to that topic in the requester on startup for the transport (since its deterministic for all replies to that endpoint anyway).

**Pull request closed without merging**
